
module.exports = {
    getCartInfo(){
        let cartInfo = {
          "title":"购物车",
          "login":{
            "pic":"assets/cart/img/4.png",
            "name":"登录后才能看见商品哦"
          },
          "body":{
            "title":"为你推荐",
            "con":[
              {
                "id":0,
                "lsp":"3色可选",
                "pic":"assets/cart/img/1.png",
                "rsp":"特价",
                "bp":"AMAZFIT 米动手表青春...",
                "sp":"智能手表全民化",
                "money":"279起",
                "num":1
              },
              {
                "id":1,
                "lsp":"3色可选",
                "pic":"assets/cart/img/9.png",
                "rsp":"满减",
                "bp":"滑盖式自动喷香机",
                "sp":"无痕壁挂",
                "money":"39.9起",
                "num":1
              },
              {
                "id":2,
                "lsp":"5色可选",
                "pic":"assets/cart/img/7.png",
                "rsp":"满减",
                "bp":"AMAZFIT智能手表2",
                "sp":"4G自由通话，3D水荡屏",
                "money":"999起",
                "num":1
              },
              {
                "id":3,
                "lsp":"1色可选",
                "pic":"assets/cart/img/2.png",
                "rsp":"满减",
                "bp":"茅台飞天酒43度500ml",
                "sp":"酱香突出酒体醇厚",
                "money":"999起",
                "num":1
              },
              {
                "id":4,
                "lsp":"3色可选",
                "pic":"assets/cart/img/9.png",
                "rsp":"满减",
                "bp":"滑盖式自动喷香机",
                "sp":"无痕壁挂",
                "money":"39.9起",
                "num":1
              },
              {
                "id":5,
                "lsp":"3色可选",
                "pic":"assets/cart/img/1.png",
                "rsp":"特价",
                "bp":"AMAZFIT 米动手表青春...",
                "sp":"智能手表全民化",
                "money":"279起",
                "num":1
              },
              {
                "id":6,
                "lsp":"1色可选",
                "pic":"assets/cart/img/2.png",
                "rsp":"满减",
                "bp":"茅台飞天酒43度500ml",
                "sp":"酱香突出酒体醇厚",
                "money":"999起",
                "num":1
              },
              {
                "id":7,
                "lsp":"5色可选",
                "pic":"assets/cart/img/7.png",
                "rsp":"满减",
                "bp":"AMAZFIT智能手表2",
                "sp":"4G自由通话，3D水荡屏",
                "money":"999起",
                "num":1
              },
            ],
            "checked":true,
            "fchecked":true,
            "shops":[
              {
                "id":9,
                "pic":"assets/upday/img/b40948876.jpg",
                "title":"小米手表",
                "money":1299,
                "checked":true,
                "num":1
            },
            {
              "id":10,
                "pic":"assets/upday/img/9d47e5eb4.jpg",
                "title":"智能晾衣机",
                "money":999,
                "checked":true,
                "num":1
            },
            { 
              "id":11,
                "pic":"assets/upday/img/720cd980ff2.jpg",
                "title":"小米CC9 Pro",
                "money":3099,
                "checked":true,
                "num":1
            }
            ]
          },
          "footer":[
            {
              "pic":"assets/sort/img/0191014212018.png",
              "content":"首页"
            },
            {
              "pic":"assets/home/img/20191014190536.png",
              "content":"分类"
            },
            {
              "pic":"assets/home/img/20191014190604.png",
              "content":"品味"
            },
            {
              "pic":"assets/cart/img/0191015194453.png",
              "content":"购物车"
            },
            {
              "pic":"assets/home/img/0191014190628.png",
              "content":"我的"
            }
          ]
        }
        return cartInfo
    }
}

