module.exports = {
    getHomeInfo(){
        let homeInfo = {
            "header":{
                "picLeft":"assets/home/img/20191014163815.png",
                "picRight":"assets/home/img/20191014163707.png",
                "picFoot":"assets/home/img/a1.png",
                "picFoot2":"assets/home/img/1106210437.png",
                "picFoot3":"assets/home/img/1106210459.png",
                "picFoot4":"assets/home/img/1106210512.png"
            },
            "body":{
                "topProduct":[
                    {
                        "pic":"assets/home/img/1_05.gif",
                        "name":"每日上新"
                    },
                    {
                        "pic":"assets/home/img/1_05.gif",
                        "name":"小米众筹"
                    },
                    {
                        "pic":"assets/home/img/1_07.gif",
                        "name":"限时抢购"
                    },
                    {
                        "pic":"assets/home/img/1_09.gif",
                        "name":"热销排行"
                    },
                    {
                        "pic":"assets/home/img/1_11.gif",
                        "name":"一元拼团"
                    },
                    {
                        "pic":"assets/home/img/1_18.gif",
                        "name":"小米自营"
                    },
                    {
                        "pic":"assets/home/img/1_19.gif",
                        "name":"智能家庭"
                    },
                    {
                        "pic":"assets/home/img/1_20.gif",
                        "name":"手机精选"
                    },
                    {
                        "pic":"assets/home/img/1_21.gif",
                        "name":"家用电器"
                    },
                    {
                        "pic":"assets/home/img/1_22.jpg",
                        "name":"家具家装"
                    }
                ],
                "sectionpic":"assets/home/img/0191014185103.png",
                "footProduct":[
                    {
                        "pic":"assets/home/img/0191014185411.png",
                    },
                    {
                        "pic":"assets/home/img/20191014185430.png"
                    },
                    {
                        "pic":"assets/home/img/0191014185515.png"
                    },
                    {
                        "pic":"assets/home/img/20191014185620.png"
                    }
                ],
                "pic":"assets/home/img/106210119.png",
                "pic2":"assets/home/img/106210210.png"
            },
            "footer":[
                {
                    "pic":"assets/home/img/0191014190500.png",
                    "content":"首页"
                },
                {
                    "pic":"assets/home/img/20191014190536.png",
                    "content":"分类"
                },
                {
                    "pic":"assets/home/img/20191014190604.png",
                    "content":"品味"
                },
                {
                    "pic":"assets/home/img/0191014190617.png",
                    "content":"购物车"
                },
                {
                    "pic":"assets/home/img/0191014190628.png",
                    "content":"我的"
                }
            ]
        }
        return homeInfo
    }
}