module.exports = {
    getMineInfo(){
        let getMineInfo = {
            "header":{
                "lpic":"assets/mine/img/91015201828.png",
                "rpic":"assets/mine/img/191015201437.png",
                "con":"请登录"
            },
            "body":{
                "op":"我的订单",
                "op2":"全部订单",
                "oc":[
                    {
                        "pic":"assets/mine/img/0191015195331.png",
                        "con":"待付款"
                    },
                    {
                        "pic":"assets/mine/img/20191015195405.png",
                        "con":"待收货"
                    },
                    {
                        "pic":"assets/mine/img/20191015195418.png",
                        "con":"待评价"
                    },
                    {
                        "pic":"assets/mine/img/0191015195434.png",
                        "con":"退款/售后"
                    }
                ],
                "pp":"我的功能",
                "pc":[
                    {
                        "pic":"assets/mine/img/191015195447.png",
                        "con":"0张优惠券"
                    },
                    {
                        "pic":"assets/mine/img/0191015195503.png",
                        "con":"我的收藏"
                    },
                    {
                        "pic":"assets/mine/img/191015195518.png",
                        "con":"浏览记录"
                    },
                    {
                        "pic":"assets/mine/img/191015195528.png",
                        "con":"地址管理"
                    }
                ],
                "pic":"assets/home/img/0191014185103.png",
                "tp":"更多工具",
                "tc":[
                    {
                        "pic":"assets/mine/img/191015195604.png",
                        "con":"我的资产"
                    },
                    {
                        "pic":"assets/mine/img/0191015195621.png",
                        "con":"小米钱包"
                    },
                    {
                        "pic":"assets/mine/img/191015195633.png",
                        "con":"拼团"
                    },
                    {
                        "pic":"assets/mine/img/0191015195644.png",
                        "con":"我要定制"
                    },
                    {
                        "pic":"assets/mine/img/191015195659.png",
                        "con":"官方客服"
                    },
                    {
                        "pic":"assets/mine/img/191015195714.png",
                        "con":"用户反馈"
                    },
                    {
                        "pic":"assets/mine/img/191015195725.png",
                        "con":"资质证照"
                    },
                    {
                        "pic":"assets/mine/img/191015195739.png",
                        "con":"协议规则"
                    }
                ]
            },
            "footer":[
                {
                    "pic":"assets/sort/img/0191014212018.png",
                    "name":"首页"
                },
                {
                    "pic":"assets/home/img/20191014190536.png",
                    "name":"分类"
                },
                {
                    "pic":"assets/home/img/20191014190604.png",
                    "name":"品味"
                },
                {
                    "pic":"assets/home/img/0191014190617.png",
                    "name":"购物车"
                },
                {
                    "pic":"assets/mine/img/0191015215024.png",
                    "name":"我的"
                }
            ]
        }
        return getMineInfo
    }
}