module.exports = {
    getSortInfo(){
        let sortInfo = {
            "pic":"assets/sort/img/8.jpg",
            "nav":[
                {   
                    "title":"精品推荐",
                    "content":{
                        "title":"为你推荐",
                        "content":[
                            {
                                "pic":"assets/sort/img/1.png",
                                "name":"空调"
                            },
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            },
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"精选专区",
                        "content":[
                            {
                                "pic":"assets/sort/img/5.png",
                                "name":"热销榜单"
                            },
                            {
                                "pic":"assets/sort/img/4.png",
                                "name":"出游必备"
                            },
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            }
                        ]
                    }
                },
                {
                    "title":"智能家庭",
                    "content":{
                        "title":"专属定制",
                        "content":[
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            },
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"智能家居",
                        "content":[
                            {
                                "pic":"assets/sort/img/4.png",
                                "name":"出游必备"
                            },
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            }
                        ]
                    }
                },
                {
                    "title":"家具家装",
                    "content":{
                        "title":"爆款推荐",
                        "content":[
                            {
                                "pic":"assets/sort/img/1.png",
                                "name":"空调"
                            },
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            },
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"家具",
                        "content":[
                            {
                                "pic":"assets/sort/img/5.png",
                                "name":"热销榜单"
                            },
                            {
                                "pic":"assets/sort/img/4.png",
                                "name":"出游必备"
                            },
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            }
                        ]
                    }
                },
                {
                    "title":"居家餐厨",
                    "content":{
                        "title":"家纺",
                        "content":[
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            },
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"锅具",
                        "content":[
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            }
                        ]
                    }
                },
                {
                    "title":"日用文创",
                    "content":{
                        "title":"清洁用具",
                        "content":[
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            },
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电脑"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"日用杂货",
                        "content":[
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            },
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            }
                        ]
                    }
                },
                {
                    "title":"电视影音",
                    "content":{
                        "title":"电视",
                        "content":[
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"投影",
                        "content":[
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                        ]
                    }
                },
                {
                    "title":"手机电脑",
                    "content":{
                        "title":"手机",
                        "content":[
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"电脑",
                        "content":[
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            },
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电脑"
                            }
                        ]
                    }
                },
                {
                    "title":"数码周边",
                    "content":{
                        "title":"热门精选",
                        "content":[
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            },
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电脑"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"电脑外设",
                        "content":[
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            }
                        ]
                    }
                },
                {
                    "title":"服装配饰",
                    "content":{
                        "title":"外套羽绒服",
                        "content":[
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"卫衣衬衫",
                        "content":[
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            },
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电脑"
                            }
                        ]
                    }
                },
                {
                    "title":"鞋靴箱包",
                    "content":{
                        "title":"男鞋",
                        "content":[
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"女鞋",
                        "content":[
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电脑"
                            }
                        ]
                    }
                },
                {
                    "title":"运动户外",
                    "content":{
                        "title":"畅销推荐",
                        "content":[
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电脑"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"健身训练",
                        "content":[
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            },
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            }
                        ]
                    }
                },
                {
                    "title":"出行车品",
                    "content":{
                        "title":"骑行用品",
                        "content":[
                            {
                                "pic":"assets/sort/img/5.png",
                                "name":"热销榜单"
                            },
                            {
                                "pic":"assets/sort/img/4.png",
                                "name":"出游必备"
                            },
                            {
                                "pic":"assets/sort/img/3.png",
                                "name":"小爱专区"
                            },
                            {
                                "pic":"assets/sort/img/15.png",
                                "name":"品质生活"
                            },
                            {
                                "pic":"assets/sort/img/11.png",
                                "name":"运动健康"
                            },
                            {
                                "pic":"assets/sort/img/13.png",
                                "name":"居家必备"
                            }
                        ]
                    },
                    "nextContent":{
                        "title":"汽车用品",
                        "content":[
                            {
                                "pic":"assets/sort/img/1.png",
                                "name":"空调"
                            },
                            {
                                "pic":"assets/sort/img/2.png",
                                "name":"手表"
                            },
                            {
                                "pic":"assets/sort/img/10.png",
                                "name":"耳机"
                            },
                            {
                                "pic":"assets/sort/img/7.png",
                                "name":"电视机"
                            },
                            {
                                "pic":"assets/sort/img/12.png",
                                "name":"行李箱"
                            },
                            {
                                "pic":"assets/sort/img/9.png",
                                "name":"灯具"
                            }
                        ]
                    }
                }
            ],
            "footer":[
                {
                    "pic":"assets/sort/img/0191014212018.png",
                    "content":"首页"
                },
                {
                    "pic":"assets/sort/img/0191014212050.png",
                    "content":"分类"
                },
                {
                    "pic":"assets/home/img/20191014190604.png",
                    "content":"品味"
                },
                {
                    "pic":"assets/home/img/0191014190617.png",
                    "content":"购物车"
                },
                {
                    "pic":"assets/home/img/0191014190628.png",
                    "content":"我的"
                }
            ]
        }
        return sortInfo
    }
}