module.exports = {
    getTasteInfo(){
        let tasteInfo = {
            "header":{
                "pic":"assets/taste/img/191015160154.png",
                "mf":"我的关注",
                "title":[
                    {
                        "name":"精选"
                    },
                    {
                        "name":"品牌甄选"
                    },
                    {
                        "name":"智能家居"
                    },
                    {
                        "name":"生活日用"
                    }
                ]
            },
            "body":[
                {
                    "icon":"assets/taste/img/20191015160411.png",
                    "name":"有品小助手",
                    "pin":"官方品牌",
                    "mf":"+关注",
                    "content":"Hi 大家好，我是有品小助手",
                    "pic":"assets/taste/img/20191015160435.png",
                    "reader":"8150阅读"
                },
                {
                    "icon":"assets/taste/img/0191015160506.png",
                    "name":"咖哥",
                    "pin":"官方品牌",
                    "mf":"+关注",
                    "content":"新品首发：历经三个多月，选料、开模、设计打样、佚",
                    "content2":"代设计十多次，反复打样优化每一处细节，终现臻品，",
                    "content3":"设计优雅，性价比极佳。...",
                    "text":"查看全文",
                    "pic":"assets/taste/img/0191015160635.png",
                },
                {
                    "icon":"assets/taste/img/20191015160411.png",
                    "name":"有品小助手",
                    "pin":"官方品牌",
                    "mf":"+关注",
                    "content":"Hi 大家好，我是有品小助手",
                    "pic":"assets/taste/img/9d80b7c.jpg",
                    "reader":"8150阅读"
                },
                {
                    "icon":"assets/taste/img/0191015160506.png",
                    "name":"咖哥",
                    "pin":"官方品牌",
                    "mf":"+关注",
                    "content":"新品首发：历经三个多月，选料、开模、设计打样、佚",
                    "content2":"代设计十多次，反复打样优化每一处细节，终现臻品，",
                    "content3":"设计优雅，性价比极佳。...",
                    "text":"查看全文",
                    "pic":"assets/taste/img/0191015160635.png",
                }
            ],
            "footer":[
                {
                    "pic":"assets/sort/img/0191014212018.png",
                    "name":"首页"
                },
                {
                    "pic":"assets/home/img/20191014190536.png",
                    "name":"分类"
                },
                {
                    "pic":"assets/taste/img/0191015160652.png",
                    "name":"品味"
                },
                {
                    "pic":"assets/home/img/0191014190617.png",
                    "name":"购物车"
                },
                {
                    "pic":"assets/home/img/0191014190628.png",
                    "name":"我的"
                }
            ]
        }
        return tasteInfo
    }
}