module.exports = {
    getUpdayInfo(){
        let updayInfo = {
            "header":{
                "icon":"assets/group/img/20191019144638.png",
                "pic":"assets/upday/img/t4t3t.png",
                "banner":[
                    {
                        "pic":"assets/upday/img/)DBV{{3.png"
                    },
                    {
                        "pic":"assets/upday/img/T[8[N_@I.png"
                    },
                    {
                        "pic":"assets/upday/img/){J[~CPWK.png"
                    },
                    {
                        "pic":"assets/upday/img/QC{HE~RYCC.png"
                    },
                    {
                        "pic":"assets/upday/img/40T_J_G.png"
                    }
                ]
            },
            "body":{
                "title":"今日上新",
                "sp":"每天0点 新奇发布",
                "con":[
                    {
                        "pic":"assets/upday/img/b40948876.jpg",
                        "title":"小米手表",
                        "sp":"打电话上网，健康监测",
                        "icon":"assets/upday/img/3506ddfbce.png",
                        "lsp":"到手价",
                        "rsp":"￥1299起"
                    },
                    {
                        "pic":"assets/upday/img/9d47e5eb4.jpg",
                        "title":"智能晾衣机",
                        "sp":"30KG承重，一键升降",
                        "icon":"assets/upday/img/a1fd1b24d0.png",
                        "rsp":"￥929起",
                        "sp3":"￥999"
                    },
                    {
                        "pic":"assets/upday/img/720cd980ff2.jpg",
                        "title":"小米CC9 Pro",
                        "sp":"1亿像素手机影像新篇章",
                        "icon":"assets/upday/img/3506ddfbce.png",
                        "lsp":"到手价",
                        "rsp":"￥3099起"
                    },
                    {
                        "pic":"assets/upday/img/dc9ea834.png",
                        "title":"贝医生声波美牙仪",
                        "sp":"领取大额满减券，到手价299元",
                        "rsp":"￥399"
                    },
                    {
                        "pic":"assets/upday/img/5d4237c20158a.jpg",
                        "title":"美标大冲力马桶",
                        "sp":"两路水洗冲洗，持久不挂污",
                        "rsp":"￥999"
                    },
                    {
                        "pic":"assets/upday/img/bdaeb6d3d12.jpg",
                        "title":"摩卡橡木餐桌椅",
                        "sp":"北美红橡木，榫卯工艺，环抱设计",
                        "rsp":"￥1469起"
                    },
                    {
                        "pic":"assets/upday/img/6eaafc03.jpg",
                        "title":"眼部按摩仪4301",
                        "sp":"3D机械式按摩",
                        "rsp":"￥499"
                    },
                    {
                        "pic":"assets/upday/img/28e1efa92fd.jpg",
                        "title":"免手洗平板拖把",
                        "sp":"洗脱一体，真免手洗",
                        "rsp":"￥99"
                    },
                    {
                        "pic":"assets/upday/img/838b72f87fd.jpg",
                        "title":"流浪星球艺术吊灯",
                        "sp":"星球造型，重工混色玻璃",
                        "rsp":"￥459"
                    },
                    {
                        "pic":"assets/upday/img/d04bf9dd1d4.jpg",
                        "title":"【券后惊喜价】雅诗兰黛红石榴..",
                        "sp":"有效抗氧化，深度滋润防初老",
                        "rsp":"￥772"
                    },
                    {
                        "pic":"assets/upday/img/cf1124910f9.jpg",
                        "title":"秒秒收婴儿推车",
                        "sp":"自重折叠，超大座宽，坐躺两用",
                        "rsp":"￥1099"
                    },
                    {
                        "pic":"assets/upday/img/43739e795.jpg",
                        "title":"百雀羚面膜20片",
                        "sp":"保湿补水，提亮肤色",
                        "rsp":"￥99"
                    },
                    {
                        "pic":"assets/upday/img/553674ac85.jpg",
                        "title":"旅途轻户外低帮鞋",
                        "sp":"耐磨大底，稳定后跟",
                        "icon":"assets/upday/img/3506ddfbce.png",
                        "lsp":"到手价",
                        "rsp":"￥1299起",
                        "sp3":"￥279"
                    },
                    {
                        "pic":"assets/upday/img/6531f671c5.jpg",
                        "title":"小米电视5 65英寸",
                        "sp":"金属机身，一体折弯边框",
                        "rsp":"￥3999"
                    },
                    {
                        "pic":"assets/upday/img/d1bde02.jpg",
                        "title":"小米电视5 55英寸",
                        "sp":"全面屏设计，薄至5.9mm",
                        "rsp":"￥2999"
                    },
                    {
                        "pic":"assets/upday/img/eaad810b.jpg",
                        "title":"2016大拉菲葡萄酒",
                        "sp":"领券立减300",
                        "rsp":"￥6999"
                    }
                ]
            }
        }
        return updayInfo
    }
}